### ISSUE TITLE
load the meta table in query server

### ISSUE THREAD

**Issue by at15** [at15/tree-index#2]
- [ ] start a dropwizard server
- [ ] load the meta table when start
- [ ] count execute time
- [ ] use redis as result cache
- [ ] show the query process

**Comment by at15** [comment]
may use spring boot to generate a server
